
const fs = require('fs');
const path = require('path');

const files = [
    'public/data/moves_chunk_0.json',
    'public/data/moves_chunk_1.json'
];

const replacements = [
    // Move names/types/etc are already mostly ok, focusing on description and higherLevels
    { r: /Faça um ataque à distância on a creature/g, s: 'Faça um ataque à distância contra uma criatura' },
    { r: /the creature takes/g, s: 'a criatura recebe' },
    { r: /grass damage/g, s: 'dano de planta' },
    { r: /rock damage/g, s: 'dano de pedra' },
    { r: /poison damage/g, s: 'dano de veneno' },
    { r: /flying damage/g, s: 'dano voador' },
    { r: /dark damage/g, s: 'dano sombrio' },
    { r: /ghost damage/g, s: 'dano fantasma' },
    { r: /bug damage/g, s: 'dano de inseto' },
    { r: /fighting damage/g, s: 'dano lutador' },
    { r: /ice damage/g, s: 'dano de gelo' },
    { r: /steel damage/g, s: 'dano de aço' },
    { r: /water damage/g, s: 'dano de água' },
    { r: /normal damage/g, s: 'dano normal' },
    { r: /psychic damage/g, s: 'dano psíquico' },
    { r: /electric damage/g, s: 'dano elétrico' },
    { r: /fire damage/g, s: 'dano de fogo' },
    { r: /dragon damage/g, s: 'dano de dragão' },
    { r: /ground damage/g, s: 'dano de terra' },
    { r: /fairy damage/g, s: 'dano de fada' },
    
    { r: /and (\d+d\d+) at level (\d+)/g, s: 'e $1 no nível $2' },
    { r: /At level (\d+)/g, s: 'No nível $1' },
    { r: /at level (\d+)/g, s: 'no nível $1' },
    
    { r: /You attempt to absorb some of an enemy’s health\./g, s: 'Você tenta absorver um pouco da vida de um inimigo.' },
    { r: /Faster than a blink of an eye, you smack the opponent with a bit of rock\./g, s: 'Mais rápido que um piscar de olhos, você atinge o oponente com um pedaço de rocha.' },
    { r: /You may move up to your speed and/g, s: 'Você pode se mover até o seu deslocamento e' },
    { r: /You create a stream of hot acid and aim it at your enemy\./g, s: 'Você cria um jato de ácido quente e o direciona ao seu inimigo.' },
    { r: /Faça uma jogada de ataque à distância, doing/g, s: 'Faça uma jogada de ataque à distância, causando' },
    { r: /Em um acerto\./g, s: 'em um acerto.' },
    { r: /You are surrounded by a shield of thick acid for the duração\./g, s: 'Você é cercado por um escudo de ácido espesso pela duração.' },
    { r: /During this time, your AC increases by 2, and any Pokémon that hits you with a melee attack takes/g, s: 'Durante esse tempo, sua CA aumenta em 2 e qualquer Pokémon que te atingir com um ataque corpo a corpo recebe' },
    { r: /You spit a spray of acid in a 15 foot cone originating from yourself\./g, s: 'Você cospe um spray de ácido em um cone de 15 pés originando de você mesmo.' },
    { r: /Each creature in the area must make a Constituição teste de resistência contra a sua CD de MOVE\./g, s: 'Cada criatura na área deve fazer um teste de resistência de Constituição contra a sua CD de MOVE.' },
    { r: /Em uma falha the creature takes/g, s: 'Em uma falha, a criatura recebe' },
    { r: /and has disadvantage on its next teste de resistência\./g, s: 'e tem desvantagem em seu próximo teste de resistência.' },
    { r: /Em um sucesso they take half damage and do not get the disadvantage on their teste de resistência\./g, s: 'Em um sucesso, ela recebe metade do dano e não recebe desvantagem em seu teste de resistência.' },
    { r: /You move through the battlefield, making a quick succession of strikes\./g, s: 'Você se move pelo campo de batalha, fazendo uma sucessão rápida de ataques.' },
    { r: /When you use this ação you do not take attacks of opportunity until the end of your turn\./g, s: 'Quando você usa esta ação, você não recebe ataques de oportunidade até o fim do seu turno.' },
    { r: /You may make three melee attacks against different targets as you move\./g, s: 'Você pode fazer três ataques corpo a corpo contra alvos diferentes enquanto se move.' },
    { r: /Each attack does/g, s: 'Cada ataque causa' },
    { r: /You use a secret technique to calm and cleanse yourself\./g, s: 'Você usa uma técnica secreta para se acalmar e se purificar.' },
    { r: /When you use this move you can end one effect on yourself that is causing you to be charmed, frightened, paralyzed, poisoned, flinched, or stunned\./g, s: 'Quando você usa este movimento, você pode encerrar um efeito em si mesmo que esteja causando as condições: encantado, amedrontado, paralisado, envenenado, recuado ou atordoado.' },
    { r: /From the air you slash into and through the target\./g, s: 'Do ar, você corta o alvo.' },
    { r: /If you can be airborne this turn, Faça um ataque corpo a corpo with advantage doing/g, s: 'Se você puder estar no ar neste turno, faça um ataque corpo a corpo com vantagem causando' },
    { r: /You politely let your ally take the initiative\./g, s: 'Você educadamente deixa seu aliado tomar a iniciativa.' },
    { r: /Choose a willing creature that you can see dentro do alcance\./g, s: 'Escolha uma criatura voluntária que você possa ver dentro do alcance.' },
    { r: /Until the spell ends, the target's deslocamento is doubled, it gains a \+2 bonus to AC, it has advantage on Destreza teste de resistências, and gains an additional ação on each of its turns\./g, s: 'Até o feitiço acabar, o deslocamento do alvo é dobrado, ele ganha um bônus de +2 na CA, tem vantagem em testes de resistência de Destreza e ganha uma ação adicional em cada um de seus turnos.' },
    { r: /That ação can only be used to take the Dash, Disengage, Hide or Use an Object ação\./g, s: 'Essa ação só pode ser usada para as ações de Disparada, Desengajar, Esconder ou Usar um Objeto.' },
    { r: /When this move ends, the target can't move or take açãos até o fim de seu próximo turno\./g, s: 'Quando este movimento termina, o alvo não pode se mover ou realizar ações até o fim do seu próximo turno.' },
    { r: /You hone in on your abilities and feel a surge of speed course through your veins\./g, s: 'Você aprimora suas habilidades e sente uma onda de velocidade percorrer suas veias.' },
    { r: /As long as you have the type, increase your walking, flying, or swimming deslocamento by (\d+) pés for the duração\./g, s: 'Enquanto você tiver o tipo, aumente seu deslocamento de caminhada, voo ou natação em $1 pés pela duração.' },
    { r: /You can only increase each type of your deslocamento by (\d+) pés total with this move\./g, s: 'Você só pode aumentar cada tipo de seu deslocamento em $1 pés no total com este movimento.' },
    { r: /You send a razor sharp slice of air towards your opponent\./g, s: 'Você envia uma lâmina de ar afiada em direção ao seu oponente.' },
    { r: /against an opponent dealing/g, s: 'contra um oponente causando' },
    { r: /This move crits on a natural roll of 19 or 20\./g, s: 'Este movimento causa um acerto crítico em uma rolagem natural de 19 ou 20.' },
    { r: /You conjure up a powerful slice of compacted air and hurl it at an enemy Pokémon\./g, s: 'Você conjura uma lâmina poderosa de ar compactado e a lança contra um Pokémon inimigo.' },
    { r: /doing (.*) em um acerto bem-sucedido\./g, s: 'causando $1 em um acerto bem-sucedido.' },
    { r: /If the natural roll for this attack is 18 or higher, the target becomes flinched\./g, s: 'Se a rolagem natural para este ataque for 18 ou superior, o alvo fica recuado.' },
    { r: /You use your psychic abilities to teleport yourself and an ally\./g, s: 'Você usa suas habilidades psíquicas para teletransportar você e um aliado.' },
    { r: /Pick one willing creature dentro do alcance\./g, s: 'Escolha uma criatura voluntária dentro do alcance.' },
    { r: /You and that creature swap positions\./g, s: 'Você e essa criatura trocam de posição.' },
    { r: /If either you or your target is too large to fit in their new spot, this move does nothing\./g, s: 'Se você ou seu alvo for muito grande para caber no novo local, este movimento não faz nada.' },
    { r: /Your mind elevates to a new level of focus\./g, s: 'Sua mente se eleva a um novo nível de foco.' },
    { r: /Add \+5 to any teste de resistência you make for the duração, but select one of your other moves\./g, s: 'Adicione +5 a qualquer teste de resistência que você fizer pela duração, mas selecione um de seus outros movimentos.' },
    { r: /You forget that move and cannot use it for the duração\./g, s: 'Você esquece esse movimento e não pode usá-lo pela duração.' },
    { r: /You cannot have the bonus from amnesia more than once\./g, s: 'Você não pode ter o bônus de amnésia mais de uma vez.' },
    { r: /You fire an anchor attached to a chain straight at your opponent\./g, s: 'Você dispara uma âncora presa a uma corrente diretamente em seu oponente.' },
    { r: /at your opponent, causando/g, s: 'contra seu oponente, causando' },
    { r: /If you hit this attack you may choose immediately pull your target up to (\d+) pés towards yourself\./g, s: 'Se você acertar este ataque, você pode escolher puxar imediatamente seu alvo até $1 pés em sua direção.' },
    { r: /You levitate a pile of earth and crush an enemy Pokémon with it\./g, s: 'Você levita uma pilha de terra e esmaga um Pokémon inimigo com ela.' },
    { r: /You surround yourself in a stream of water which lets you speed through battle\./g, s: 'Você se cerca de um fluxo de água que permite que você se mova rapidamente pela batalha.' },
    { r: /Rings of healing water surround you\./g, s: 'Anéis de água curativa cercam você.' },
    { r: /While the rings exist, you heal (.*) each turn at the end of your turn\./g, s: 'Enquanto os anéis existirem, você cura $1 a cada turno no final do seu turno.' },
    { r: /You surround your tail with a whirling current and slam it into our foe\./g, s: 'Você envolve sua cauda com uma corrente rodopiante e a bate em seu inimigo.' },
    { r: /against an opponent, causando/g, s: 'contra um oponente, causando' },
    { r: /You thrust out an open hand and unleash relentless strikes against a Pokémon\./g, s: 'Você estende a mão aberta e libera ataques implacáveis contra um Pokémon.' },
    { r: /After successfully hitting a target, roll a d4\./g, s: 'Após atingir um alvo com sucesso, role um d4.' },
    { r: /On a result of 3 or 4, you may immediately hit again for an additional/g, s: 'Em um resultado de 3 ou 4, você pode atingir novamente imediatamente por um adicional de' },
    { r: /Continue this process until you fail to roll a 3 or 4 on the d4 roll\./g, s: 'Continue este processo até falhar em rolar um 3 ou 4 no d4.' },
    { r: /A sweet refreshing wind gently blows\./g, s: 'Um vento doce e refrescante sopra suavemente.' },
    { r: /This Pokémon makes a medicine check\./g, s: 'Este Pokémon faz um teste de Medicina.' },
    { r: /If the result of the check is higher than the DC to remove a status effect on any creature within (\d+) pés \(line of sight\) from the caster, the effect is removed\./g, s: 'Se o resultado do teste for maior que a CD para remover um efeito de status em qualquer criatura dentro de $1 pés (linha de visão) do conjurador, o efeito é removido.' },
    { r: /If there is no DC to remove the status effect, the effective DC is 15\./g, s: 'Se não houver CD para remover o efeito de status, a CD efetiva é 15.' },
    { r: /You exude a sweet perfume, bolstering your ally's resolve\./g, s: 'Você exala um perfume doce, reforçando a determinação de seu aliado.' },
    { r: /For the duração of this move whenever you or a friendly creature within (\d+) pés of you makes a teste de resistência, the creature gains a bonus to the teste de resistência equal to your Charisma modifier \(with a minimum bonus of \+1\)\./g, s: 'Pela duração deste movimento, sempre que você ou uma criatura amigável dentro de $1 pés de você fizer um teste de resistência, a criatura ganha um bônus no teste de resistência igual ao seu modificador de Carisma (com um bônus mínimo de +1).' },
    { r: /You try to be as helpful as possible\./g, s: 'Você tenta ser o mais útil possível.' },
    { r: /For the duração you can use the help ação as a bonus ação\./g, s: 'Pela duração, você pode usar a ação de Ajuda como uma ação bônus.' },
    { r: /You slap your opponent on the back, making sure they know you'll be there for them \(when they die, cause you're killing them\)\./g, s: 'Você dá um tapa nas costas do seu oponente, garantindo que ele saiba que você estará lá por ele (quando ele morrer, porque você o está matando).' },
    { r: /If you directly damaged your target since the start of your previous turn, you have advantage on the attack roll\./g, s: 'Se você causou dano diretamente ao seu alvo desde o início do seu turno anterior, você tem vantagem na jogada de ataque.' },
    { r: /You make a face or feint a movement\./g, s: 'Você faz uma careta ou finge um movimento.' },
    { r: /If the target can see you, it must succeed on a Sabedoria teste de resistência or take/g, s: 'Se o alvo puder ver você, ele deve ser bem-sucedido em um teste de resistência de Sabedoria ou receber' },
    { r: /and become flinched\./g, s: 'e ficar recuado.' },
    { r: /You send out your swarm in a vicious biting, stinging attack\./g, s: 'Você envia seu enxame em um ataque vicioso de picadas e mordidas.' },
    { r: /This move lands a critical hit on an attack roll of 19 or 20\./g, s: 'Este movimento desfere um acerto crítico em uma jogada de ataque de 19 ou 20.' },
    { r: /You are the cutest\./g, s: 'Você é a coisa mais fofa.' },
    { r: /One creature of a gender different than yours dentro do alcance must succeed Charisma teste de resistência or be charmed for the duração, or until you or your companions do anything harmful to it\./g, s: 'Uma criatura de um gênero diferente do seu dentro do alcance deve ser bem-sucedida em um teste de resistência de Carisma ou ficará encantada pela duração, ou até que você ou seus companheiros façam algo prejudicial a ela.' },
    { r: /You gather your spirit in a compact ball of energy and fire it at an enemy\./g, s: 'Você reúne seu espírito em uma bola compacta de energia e a dispara contra um inimigo.' },
    { r: /Faça uma jogada de ataque à distância with advantage, causando/g, s: 'Faça uma jogada de ataque à distância com vantagem, causando' },
    { r: /You create a 60-foot long, 5-foot wide line of glowing but freezing cold light\./g, s: 'Você cria uma linha de 60 pés de comprimento e 5 pés de largura de luz brilhante, mas extremamente gelada.' },
    { r: /Any creature caught in the line must make a Destreza teste de resistência, taking (.*) em uma falha or half as much em um sucesso\./g, s: 'Qualquer criatura pega na linha deve fazer um teste de resistência de Destreza, recebendo $1 em uma falha ou metade disso em um sucesso.' },
    { r: /If a creature fails the teste de resistência by 10 or more, it becomes frozen\./g, s: 'Se uma criatura falhar no teste de resistência por 10 ou mais, ela fica congelada.' },
    { r: /You surround yourself with a dancing veil of rainbow lights\./g, s: 'Você se cerca com um véu dançante de luzes arco-íris.' },
    { r: /You gain (\d+) temporary hit points for the duração\./g, s: 'Você ganha $1 pontos de vida temporários pela duração.' },
    { r: /If a creature hits you with a melee attack while you have those temporary hit points, the creature takes (\d+) dano de gelo\./g, s: 'Se uma criatura te atingir com um ataque corpo a corpo enquanto você tiver esses pontos de vida temporários, a criatura recebe $1 de dano de gelo.' },
    { r: /The temporary health and ice damage of this move increase to (\d+) no nível 5, (\d+) no nível 11, and (\d+) no nível 17\./g, s: 'A vida temporária e o dano de gelo deste movimento aumentam para $1 no nível 5, $2 no nível 11 e $3 no nível 17.' },
    { r: /You sharpen your mind and feel a surge of power throughout you\./g, s: 'Você aguça sua mente e sente uma onda de poder através de você.' },
    { r: /You deal an extra 1d4 on melee attacks for the duração\./g, s: 'Você causa 1d4 extra em ataques corpo a corpo pela duração.' },
    { r: /no nível 10 the extra damage on your melee attacks aumenta para 2d4\./g, s: 'No nível 10, o dano extra em seus ataques corpo a corpo aumenta para 2d4.' },
    { r: /You unleash a torrent of ice and snow that was loosened by a violent act\./g, s: 'Você libera uma torrente de gelo e neve que foi solta por um ato violento.' },
    { r: /Target a space dentro do alcance\./g, s: 'Alveje um espaço dentro do alcance.' },
    { r: /Draw a line from that space (\d+) pés wide and (\d+) pés long\./g, s: 'Desenhe uma linha a partir desse espaço com $1 pés de largura e $2 pés de comprimento.' },
    { r: /Any creature caught in the line must succeed on a DEX teste de resistência contra a sua CD de MOVE, taking (.*) em um teste de resistência falho, or half damage em um sucesso\./g, s: 'Qualquer criatura pega na linha deve ser bem-sucedida em um teste de resistência de Destreza contra a sua CD de MOVE, recebendo $1 em um teste de resistência falho, ou metade do dano em um sucesso.' },
    { r: /If you are below half HP, those creatures have disadvantage on the teste de resistência\./g, s: 'Se você estiver com menos da metade de seus PV, essas criaturas têm desvantagem no teste de resistência.' },
    { r: /As your opponent strikes out towards you, you give them big puppy-dog eyes\./g, s: 'Enquanto seu oponente ataca você, você olha para ele com grandes olhos de cachorrinho carente.' },
    { r: /After an attack roll against you is declared but before the roll is made you can use your reação to cause one enemy to make a Charisma teste de resistência against you MOVE DC\./g, s: 'Depois que uma jogada de ataque contra você é declarada, mas antes da rolagem ser feita, você pode usar sua reação para fazer um inimigo realizar um teste de resistência de Carisma contra sua CD de MOVE.' },
    { r: /Em uma falha that creature has disadvantage on the attack\./g, s: 'Em uma falha, essa criatura tem desvantagem no ataque.' },
    { r: /If that attack hits, you only take half damage\./g, s: 'Se esse ataque atingir, você recebe apenas metade do dano.' },
    { r: /You arm your poison spikes and point them toward your foe\./g, s: 'Você prepara seus espinhos venenosos e os aponta para o seu inimigo.' },
    { r: /As a reação when you are targeted by an attack you may increase your AC by \+5 until the start of your next turn\./g, s: 'Como uma reação quando você é alvo de um ataque, você pode aumentar sua CA em +5 até o início do seu próximo turno.' },
    { r: /You must decide to to use this move before you know if the triggering attack hits\./g, s: 'Você deve decidir usar este movimento antes de saber se o ataque disparador acerta.' },
    { r: /If your attacker is adjacent to you when you use this move and their attack misses, your attacker becomes poisoned\./g, s: 'Se o seu atacante estiver adjacente a você quando você usar este movimento e o ataque dele errar, o atacante fica envenenado.' },
    { r: /Faça um ataque à distância on a Pokémon\./g, s: 'Faça um ataque à distância contra um Pokémon.' },
    { r: /If you hit, roll 1d4\. You attack with a barrage of ranged strikes equal to the number shown\./g, s: 'Se você acertar, role um d4. Você ataca com uma barragem de ataques à distância igual ao número mostrado.' },
    { r: /Faça uma jogada de ataque à distância for each projectile\./g, s: 'Faça uma jogada de ataque à distância para cada projétil.' },
    { r: /The projectiles do (.*) each em um acerto\./g, s: 'Os projéteis causam $1 cada em um acerto.' },
    { r: /You create a transparent shield of psychic energy\./g, s: 'Você cria um escudo transparente de energia psíquica.' },
    { r: /For the duração, the barrier grants \+2 to AC for you and any allies within a 5 foot radius of you\./g, s: 'Pela duração, a barreira concede +2 na CA para você e quaisquer aliados dentro de um raio de 5 pés de você.' },
    { r: /You pass on your energy to another\./g, s: 'Você passa sua energia para outro.' },
    { r: /Choose one target you can touch\./g, s: 'Escolha um alvo que você possa tocar.' },
    { r: /You may give your ação to the target, losing your ação this turn and gaining the target an extra ação to use on their turn\./g, s: 'Você pode dar sua ação ao alvo, perdendo sua ação neste turno e concedendo ao alvo uma ação extra para usar no turno dele.' },
    { r: /You cannot use this move if you have already used your ação this turn\./g, s: 'Você não pode usar este movimento se já tiver usado sua ação neste turno.' },
    { r: /Once you use this move your turn ends immediately\./g, s: 'Assim que você usar este movimento, seu turno termina imediatamente.' },
    { r: /You gather a ferocious energy inside your beak, preparing to unleash it in a blast\./g, s: 'Você reúne uma energia feroz dentro do seu bico, preparando-se para liberá-la em uma explosão.' },
    { r: /During the duração, if you are hit by an opponent that is adjacent to you, that opponent becomes burned\./g, s: 'Durante a duração, se você for atingido por um oponente que esteja adjacente a você, esse oponente ficará queimado.' },
    { r: /As your next turn's ação, if you keep your Concentração, you unleash your stored energy\./g, s: 'Como ação do seu próximo turno, se você mantiver sua concentração, você libera sua energia armazenada.' },
    { r: /Make a range attack roll against one opponent with range, causando/g, s: 'Faça uma jogada de ataque à distância contra um oponente no alcance, causando' },
    { r: /You call upon the Força of your allies to gang up on an enemy\./g, s: 'Você invoca a força de seus aliados para atacar um inimigo em grupo.' },
    { r: /Em um acerto bem-sucedido you deal (.*) per Pokeslot your trainer has access to, then adding your MOVE modifier for additional dano sombrio\./g, s: 'Em um acerto bem-sucedido, você causa $1 por Pokeslot que seu treinador tem acesso, adicionando então seu modificador de MOVE para dano sombrio adicional.' },
    { r: /A wild Pokémon does (.*) per active ally adjacent to itself up to a maximum of 6d4, then adds their MOVE modifier\./g, s: 'Um Pokémon selvagem causa $1 por aliado ativo adjacente a si mesmo, até um máximo de 6d4, e então adiciona seu modificador de MOVE.' },
    { r: /You release a horrendous belch of digestive gases\./g, s: 'Você libera um arroto horrendo de gases digestivos.' },
    { r: /If you have eaten a berry during this combat, all the damage die for this move become d12s\./g, s: 'Se você comeu uma fruta durante este combate, todos os dados de dano para este movimento tornam-se d12s.' },
    { r: /You begin to beat your stomach and throw yourself into a battle dance\./g, s: 'Você começa a bater no estômago e se lança em uma dança de batalha.' },
    { r: /Your next successful attack does (.*) to yourself and (.*) extra normal damage to the target\./g, s: 'Seu próximo ataque bem-sucedido causa $1 a você mesmo e $2 de dano normal extra ao alvo.' },
    { r: /The damage to you and the opponent aumenta para (.*) and (.*) respectively at 5th level, (.*) and (.*) at 11th level, and (.*) and (.*) at 17th level\./g, s: 'O dano a você e ao oponente aumenta para $1 e $2 respectivamente no nível 5, $3 e $4 no nível 11 e $5 e $6 no nível 17.' },
    { r: /You use your natural affinity for others to assist in battle\./g, s: 'Você usa sua afinidade natural com os outros para ajudar na batalha.' },
    { r: /For the duração, your friends have advantage on melee attack rolls against any creature within 5 pés of you that is hostile to you\./g, s: 'Pela duração, seus amigos têm vantagem em jogadas de ataque corpo a corpo contra qualquer criatura a até 5 pés de você que seja hostil a você.' },
    { r: /You embrace the damage done to you, waiting for your time to strike\./g, s: 'Você aceita o dano causado a você, esperando o momento de atacar.' },
    { r: /You may use your ação to activate this move and keep track of all damage done to you before your next turn\./g, s: 'Você pode usar sua ação para ativar este movimento e acompanhar todo o dano causado a você antes do seu próximo turno.' },
    { r: /On your next turn, you may use your ação to lash out an an enemy with a ranged attack, striking them for double the amount of damage you took since your last turn em um acerto bem-sucedido\./g, s: 'No seu próximo turno, você pode usar sua ação para atacar um inimigo com um ataque à distância, atingindo-o pelo dobro do dano que você recebeu desde o seu último turno em um acerto bem-sucedido.' },
    { r: /At 11th Level, you can choose to hold Bide for a second turn for the chance to add additional damage to the attack\./g, s: 'No nível 11, você pode escolher manter o Bide por um segundo turno para ter a chance de adicionar dano adicional ao ataque.' },
    { r: /You attempt to grapple a target into submission\./g, s: 'Você tenta agarrar um alvo para submetê-lo.' },
    { r: /Em um acerto, the target takes (.*) and becomes grappled and restrained\./g, s: 'Em um acerto, o alvo recebe $1 e fica agarrado e impedido.' },
    { r: /At the beginning of each of its turns, it may attempt to escape with a Força teste de resistência contra a sua CD de MOVE\./g, s: 'No início de cada um dos turnos dele, ele pode tentar escapar com um teste de resistência de Força contra a sua CD de MOVE.' },
    { r: /While a Pokémon is grappled by you, you may continue to do an automatic (.*) as a bonus ação and without using PP\./g, s: 'Enquanto um Pokémon estiver agarrado por você, você pode continuar a causar automaticamente $1 como uma ação bônus e sem usar PP.' },
    { r: /The base damage aumenta para 1d12 no nível 11\./g, s: 'O dano base aumenta para 1d12 no nível 11.' },
    { r: /You sink your teeth into an enemy Pokémon\./g, s: 'Você crava seus dentes em um Pokémon inimigo.' },
    { r: /You decimate your foe with a powerful explosion of fire\./g, s: 'Você dizima seu inimigo com uma explosão poderosa de fogo.' },
    { r: /Faça uma jogada de ataque à distância doing/g, s: 'Faça uma jogada de ataque à distância causando' },
    { r: /Until the end of your next turn, your movement speed becomes zero and you cannot use damaging moves\./g, s: 'Até o final do seu próximo turno, seu deslocamento torna-se zero e você não pode usar movimentos que causam dano.' },
    { r: /The damage aumenta para 12d8 no nível 11\./g, s: 'O dano aumenta para 12d8 no nível 11.' },
    { r: /You ignite your foot with fire and kick your target\./g, s: 'Você incendeia seu pé com fogo e chuta seu alvo.' },
    { r: /If you hit your target must make a DC 10 Constituição teste de resistência or become burned\./g, s: 'Se você acertar, seu alvo deve fazer um teste de resistência de Constituição DC 10 ou ficará queimado.' },
    { r: /Icy clouds form overhead and pelt the ground with hail and snow, centered on a point you choose dentro do alcance\./g, s: 'Nuvens geladas se formam acima e bombardeiam o solo com granizo e neve, centradas em um ponto que você escolher dentro do alcance.' },
    { r: /Each Pokémon within a 10 foot radius must make a Destreza teste de resistência contra a sua CD de MOVE, taking (.*) em um teste de resistência falho, or half as much em um sucessoful one\./g, s: 'Cada Pokémon em um raio de 10 pés deve fazer um teste de resistência de Destreza contra a sua CD de MOVE, recebendo $1 em um teste de resistência falho, ou metade disso em um sucesso.' },
    { r: /By forcing your body in front of your foe, you stop their movement\./g, s: 'Ao forçar seu corpo na frente de seu inimigo, você interrompe o movimento dele.' },
    { r: /Choose one opponent dentro do alcance to make a Força teste de resistência\./g, s: 'Escolha um oponente dentro do alcance para fazer um teste de resistência de Força.' },
    { r: /Em uma falha they become restrained \(though nothing is physically holding them\)\./g, s: 'Em uma falha, eles ficam impedidos (embora nada os esteja segurando fisicamente).' },
    { r: /The target can retry the teste de resistência at the end of its turn to break the effect\./g, s: 'O alvo pode repetir o teste de resistência no final de cada um de seus turnos para encerrar o efeito.' },
    { r: /You thrust yourself towards an opponent in an attempt to crush them with your physical size\./g, s: 'Você se lança contra um oponente em uma tentativa de esmagá-lo com seu tamanho físico.' },
    { r: /Faça um ataque corpo a corpo on a target\./g, s: 'Faça um ataque corpo a corpo contra um alvo.' },
    { r: /must succeed on a DC 12 Constituição teste de resistência or become paralyzed\./g, s: 'deve ser bem-sucedido em um teste de resistência de Constituição DC 12 ou ficará paralisado.' },
    { r: /You strike a Pokémon with a club of bone\./g, s: 'Você golpeia um Pokémon com um porrete de osso.' },
    { r: /If the natural attack roll is 18 or more, the target flinches on their next turn\./g, s: 'Se a rolagem de ataque natural for 18 ou mais, o alvo recua em seu próximo turno.' },
    { r: /The base damage of the attack aumenta para 1d10 no nível 5, and 1d12 no nível 11\./g, s: 'O dano base do ataque aumenta para 1d10 no nível 5 e 1d12 no nível 11.' },
    { r: /The flinch range aumenta para 17 or more no nível 5 and 16 or more no nível 11\./g, s: 'A margem de recuo aumenta para 17 ou mais no nível 5 e 16 ou mais no nível 11.' },
    { r: /A spectral bone appears in your hand\. You make a series of quick attacks with it before it disappears\./g, s: 'Um osso espectral aparece em sua mão. Você faz uma série de ataques rápidos com ele antes que desapareça.' },
    { r: /You throw a boomerang and make two ranged attacks against a target\./g, s: 'Você lança um bumerangue e faz dois ataques à distância contra um alvo.' },
    { r: /On each successful hit you do/g, s: 'A cada acerto bem-sucedido você causa' },
    { r: /You emit a thunderous wave of sound energy\./g, s: 'Você emite uma onda estrondosa de energia sonora.' },
    { r: /Each creature in a 60 foot cone makes a Constituição teste de resistência, taking (.*) em um teste de resistência falho and half damage em um sucessoful one\./g, s: 'Cada criatura em um cone de 60 pés faz um teste de resistência de Constituição, recebendo $1 em um teste de resistência falho e metade do dano em um sucesso.' },
    { r: /You leap up into the air and come crashing down on your foe\./g, s: 'Você pula no ar e cai sobre seu inimigo.' },
    { r: /During this turn before attacking your opponent you may treat your movement as flying movement\./g, s: 'Durante este turno, antes de atacar seu oponente, você pode tratar seu movimento como movimento de voo.' },
    { r: /If you end your turn midair and cannot fly, you immediately fall after making the attack\./g, s: 'Se você terminar seu turno no ar e não puder voar, você cai imediatamente após realizar o ataque.' },
    { r: /You dive bomb the target in an all-out tackle\./g, s: 'Você mergulha sobre o alvo em uma investida total.' },
    { r: /Until the end of your next turn your movement speed is halved and you cannot fly\./g, s: 'Até o final do seu próximo turno, seu deslocamento é reduzido pela metade e você não pode voar.' },
    { r: /You strike precisely with the side of your open hand\./g, s: 'Você golpeia com precisão com o lado da mão aberta.' },
    { r: /This move destroys barriers defending the target Pokémon such as Light Screen, Reflect, and Aurora Veil\./g, s: 'Este movimento destrói barreiras que defendem o Pokémon alvo, como Tela de Luz, Reflexo e Véu Aurora.' },
    { r: /You control the water around your opponent and have them stew in the turbulent waters\./g, s: 'Você controla a água ao redor de seu oponente e o faz cozinhar nas águas turbulentas.' },
    { r: /If your opponent took water type damage since the start of your last turn this move does an additional (.*) water damage\./g, s: 'Se o seu oponente recebeu dano do tipo água desde o início do seu último turno, este movimento causa $1 de dano de água adicional.' },
    { r: /You swing your outstretched arms in a brutal circle around yourself\./g, s: 'Você balança seus braços estendidos em um círculo brutal ao seu redor.' },
    { r: /Make a single melee attack roll\. That attack targets each creature of your choice within melee range of you\./g, s: 'Faça uma única jogada de ataque corpo a corpo. Esse ataque alveja cada criatura de sua escolha dentro do seu alcance corpo a corpo.' },
    { r: /Each creature hit takes/g, s: 'Cada criatura atingida recebe' },
    { r: /You shoot a series of quickly moving bubbles at a target\./g, s: 'Você dispara uma série de bolhas que se movem rapidamente contra um alvo.' },
    { r: /Make three ranges attacks, doing/g, s: 'Faça três ataques à distância, causando' },
    { r: /You shoot a concentrated stream of bubbles in an 80-foot line, 5 pés wide\./g, s: 'Você dispara um fluxo concentrado de bolhas em uma linha de 80 pés com 5 pés de largura.' },
    { r: /Any Pokémon caught in the line must succeed on a DEX save contra a sua CD de MOVE, taking (.*) em um teste de resistência falho, or half as much em um sucessoful one\./g, s: 'Qualquer Pokémon pego na linha deve ser bem-sucedido em um teste de resistência de Destreza contra a sua CD de MOVE, recebendo $1 em um teste de resistência falho ou metade disso em um sucesso.' },
    { r: /You attack with fangs, mandibles, or the like\./g, s: 'Você ataca com presas, mandíbulas ou algo semelhante.' },
    { r: /If your opponent is holding a berry, you immediately consume that berry and gain its benefits\./g, s: 'Se o seu oponente estiver segurando uma fruta, você a consome imediatamente e ganha seus benefícios.' },
    { r: /You create series of powerful and horrifying buzzing noises\./g, s: 'Você cria uma série de ruídos de zumbido poderosos e horripilantes.' },
    { r: /Choose a number of targets equal to your MOVE modifier \(minimum one\) within 30 pés of you\./g, s: 'Escolha um número de alvos igual ao seu modificador de MOVE (mínimo um) a até 30 pés de você.' },
    { r: /Each target must make a Constituição teste de resistência, taking (.*) em um teste de resistência falho and half damage em um sucesso\./g, s: 'Cada alvo deve fazer um teste de resistência de Constituição, recebendo $1 em um teste de resistência falho e metade do dano em um sucesso.' },
    { r: /You concentrate on your physical form and flex\./g, s: 'Você se concentra em sua forma física e flexiona os músculos.' },
    { r: /You can use this move to either give yourself advantage on your next attack roll this turn, or take the dodge ação\./g, s: 'Você pode usar este movimento para ganhar vantagem em sua próxima jogada de ataque neste turno ou realizar a ação de Esquiva.' },
    { r: /You create tremors in the ground in a 20-rfoot square originating from yourself\./g, s: 'Você cria tremores no solo em um quadrado de 20 pés originando de você mesmo.' },
    { r: /All Pokémon in that area make a Destreza teste de resistência, taking (.*) em um teste de resistência falho and half damage em um sucesso\./g, s: 'Todos os Pokémon naquela área fazem um teste de resistência de Destreza, recebendo $1 em um teste de resistência falho e metade do dano em um sucesso.' },
    { r: /You harden your fist and strike out quickly\./g, s: 'Você endurece seu punho e golpeia rapidamente.' },
    { r: /You shoot a series of heavy seeds at the opponent\./g, s: 'Você dispara uma série de sementes pesadas no oponente.' },
    { r: /You inflict massive damage by burning your fire essence\./g, s: 'Você inflige dano massivo queimando sua essência de fogo.' },
    { r: /Each creature in a 60-foot long, 5-foot wide line originating from yourself must make a Destreza teste de resistência taking (.*) em uma falha and half as much em um sucesso\./g, s: 'Cada criatura em uma linha de 60 pés de comprimento e 5 pés de largura originando de você mesmo deve fazer um teste de resistência de Destreza, recebendo $1 em uma falha e metade disso em um sucesso.' },
    { r: /After you use this move you lose all resistances and vulnerabilities from your fire typing until the end of your next turn\./g, s: 'Depois de usar este movimento, você perde todas as resistências e vulnerabilidades do seu tipo fogo até o final do seu próximo turno.' },
    { r: /You take a moment to steady your will\./g, s: 'Você reserva um momento para estabilizar sua vontade.' },
    { r: /Until the end of your next turn, you have advantage on teste de resistências and enemies have disadvantage on teste de resistências you cause them to make\./g, s: 'Até o final do seu próximo turno, você tem vantagem em testes de resistência e os inimigos têm desvantagem em testes de resistência que você os obriga a fazer.' },
    { r: /You use your natural abilities to blend in with your environment\./g, s: 'Você usa suas habilidades naturais para se misturar ao ambiente.' },
    { r: /Choose one type of a Pokémon dentro do alcance\./g, s: 'Escolha um tipo de um Pokémon dentro do alcance.' },
    { r: /You gain resistance to that type for the duração of this move\./g, s: 'Você ganha resistência a esse tipo pela duração deste movimento.' },
    { r: /You draw the attention of the crowd with your spectacular moves\./g, s: 'Você atrai a atenção da multidão com seus movimentos espetaculares.' },
    { r: /Target one creature dentro do alcance to make a Sabedoria teste de resistência contra a sua CD de MOVE\./g, s: 'Alveje uma criatura dentro do alcance para fazer um teste de resistência de Sabedoria contra a sua CD de MOVE.' },
    { r: /Em uma falha they can't use a move that targets creatures other than you for the duração\./g, s: 'Em uma falha, ela não pode usar um movimento que tenha como alvo outras criaturas além de você pela duração.' },
    { r: /A creature that fails this teste de resistência can repeat the save at the end of their turn to end the effects of this move\./g, s: 'Uma criatura que falhar neste teste de resistência pode repetir o teste no final de cada um de seus turnos para encerrar os efeitos deste movimento.' },
    { r: /no nível 5 you may target one more creature with this move\./g, s: 'No nível 5 você pode alvejar mais uma criatura com este movimento.' },
    { r: /no nível 11 you can target 3 total creatures and no nível 17 you can target 4 total creatures\./g, s: 'No nível 11 você pode alvejar 3 criaturas no total e no nível 17 você pode alvejar 4 criaturas no total.' },
    { r: /You do a little dance\./g, s: 'Você faz uma dancinha.' },
    { r: /If you want, you can do 1 damage or heal 1 damage to any creature whose exact location you know\./g, s: 'Se quiser, você pode causar 1 de dano ou curar 1 de dano de qualquer criatura cuja localização exata você conheça.' },
    { r: /You take time to concentrate the electricity that is a part of your being\./g, s: 'Você dedica um tempo para concentrar a eletricidade que faz parte do seu ser.' },
    { r: /Your next attack that does electric damage does maximum damage\./g, s: 'Seu próximo ataque que causa dano elétrico causa dano máximo.' },
    { r: /You fire a bolt of electricity at your opponent, trying to capture some of the energy for yourself\./g, s: 'Você dispara um raio de eletricidade em seu oponente, tentando capturar parte da energia para si mesmo.' },
    { r: /If you roll a 19 or 20 while attacking with this move your next attack that does electric damage does maximum damage\./g, s: 'Se você rolar um 19 ou 20 enquanto ataca com este movimento, seu próximo ataque que causa dano elétrico causa dano máximo.' },
    { r: /You act as charming as possible\./g, s: 'Você age da forma mais charmosa possível.' },
    { r: /Choose one creature dentro do alcance that is not hostile towards you\./g, s: 'Escolha uma criatura dentro do alcance que não seja hostil a você.' },
    { r: /For the duração you and your trainer have advantage on all Charisma checks directed at that creature\./g, s: 'Pela duração, você e seu treinador têm vantagem em todos os testes de Carisma direcionados a essa criatura.' },
    { r: /You chatter incessantly to annoy and insult your enemy\./g, s: 'Você tagarela incessantemente para irritar e insultar seu inimigo.' },
    { r: /Choose a creature you can see\. If it can hear you, it must pass a Sabedoria save or take (.*) and have disadvantage on its next attack roll before the end of its next turn\./g, s: 'Escolha uma criatura que você possa ver. Se ela puder ouvi-lo, deve passar em um teste de resistência de Sabedoria ou receber $1 e ter desvantagem em sua próxima jogada de ataque antes do final do seu próximo turno.' },
    { r: /You strike your opponent, aiming to pierce their defenses\./g, s: 'Você golpeia seu oponente, visando perfurar suas defesas.' },
    { r: /You cannot have disadvantage on this attack\./g, s: 'Você não pode ter desvantagem neste ataque.' },
    { r: /You take hold of the opponent, spin them around you and toss them away\./g, s: 'Você agarra o oponente, gira-o ao seu redor e o arremessa para longe.' },
    { r: /The target makes a Força teste de resistência\./g, s: 'O alvo faz um teste de resistência de Força.' },
    { r: /Em uma falha, a criatura recebe (.*)\./g, s: 'Em uma falha, a criatura recebe $1.' },
    { r: /Additionally, if the target is no more than one size larger then the user, the target is pushed 10 pés in a direction of your choice and is knocked prone\./g, s: 'Adicionalmente, se o alvo não for mais do que um tamanho maior que o usuário, o alvo é empurrado 10 pés em uma direção de sua escolha e fica caído.' },
    { r: /You clamp down on an enemy, attempting keep them in place and deal massive damage\./g, s: 'Você prende um inimigo, tentando mantê-lo no lugar e causar dano massivo.' },
    { r: /Em um acerto, o alvo recebe (.*) and is grappled and restrained \(with escape DC equal to your MOVE DC\)\./g, s: 'Em um acerto, o alvo recebe $1 e fica agarrado e impedido (com CD de escape igual à sua CD de MOVE).' },
    { r: /While you are grappling a creature in this way, you may spend your ação to attack that creature again with this move without spending an additional PP\./g, s: 'Enquanto estiver agarrando uma criatura desta forma, você pode gastar sua ação para atacar essa criatura novamente com este movimento sem gastar PP adicional.' },
    { r: /You clang your scales together and imbue the sound with your essence, creating a powerful noise attack\./g, s: 'Você bate suas escamas umas nas outras e imbui o som com sua essência, criando um poderoso ataque sonoro.' },
    { r: /You lob a special glob of mud which expands into a sparkling mist\./g, s: 'Você lança um globo especial de lama que se expande em uma névoa brilhante.' },
    { r: /A 20 foot radius sphere of fog appears centered on a point you choose dentro do alcance, spreading around corners and heavily obscuring the area it fills\./g, s: 'Uma esfera de névoa de 20 pés de raio aparece centrada em um ponto que você escolher dentro do alcance, espalhando-se pelos cantos e obscurecendo pesadamente a área que preenche.' },
    { r: /The fog lasts until the end of the move's duração or until a wind of at least 10 miles per hour blows it away\./g, s: 'A névoa dura até o final da duração do movimento ou até que um vento de pelo menos 16 quilômetros por hora a afaste.' },
    { r: /You give the opponent an all out pummeling with complete disregard for your own defenses\./g, s: 'Você golpeia o oponente com tudo, desconsiderando completamente suas próprias defesas.' },
    { r: /Faça um ataque corpo a corpo against one target Pokémon\./g, s: 'Faça um ataque corpo a corpo contra um Pokémon alvo.' },
    { r: /Em um acerto deal (.*)\./g, s: 'Em um acerto, causa $1.' },
    { r: /Until the end of your next turn, attacks against you have advantage and you have -2 AC\./g, s: 'Até o final do seu próximo turno, ataques contra você têm vantagem e você tem -2 na CA.' },
    { r: /You coil up, getting ready for you next move\./g, s: 'Você se enrola, preparando-se para o seu próximo movimento.' },
    { r: /While you maintain Concentração on this move you have \+2 AC and advantage on melee attack rolls\./g, s: 'Enquanto você mantiver concentração neste movimento, você tem +2 na CA e vantagem em jogadas de ataque corpo a corpo.' },
    { r: /You strike out with a lightning fast punch\./g, s: 'Você golpeia com um soco rápido como um raio.' },
    { r: /You tell a secret to your opponent, throwing them off guard\./g, s: 'Você conta um segredo ao seu oponente, pegando-o desprevenido.' },
    { r: /Choose one opponent to make a Sabedoria teste de resistência\./g, s: 'Escolha um oponente para fazer um teste de resistência de Sabedoria.' },
    { r: /Em uma falha they have disadvantage on Força, Inteligência, and Charisma teste de resistências for the duração of this move\./g, s: 'Em uma falha, ele tem desvantagem em testes de resistência de Força, Inteligência e Carisma pela duração deste movimento.' },
    { r: /You release a ray of psychic energy meant to confuse an opponent\./g, s: 'Você libera um raio de energia psíquica destinado a confundir um oponente.' },
    { r: /Choose a target in range\. The target must make an Sabedoria teste de resistência contra a sua CD de MOVE or take (.*) and become confused\./g, s: 'Escolha um alvo no alcance. O alvo deve fazer um teste de resistência de Sabedoria contra a sua CD de MOVE ou receber $1 e ficar confundido.' },
    { r: /You attempt to enter the mind of an enemy and cause confusion\./g, s: 'Você tenta entrar na mente de um inimigo e causar confusão.' },
    { r: /Faça uma jogada de ataque à distância against a creature in range, causando (.*) em um acerto\./g, s: 'Faça uma jogada de ataque à distância contra uma criatura no alcance, causando $1 em um acerto.' },
    { r: /If you hit the target must make a Sabedoria teste de resistência contra a sua CD de MOVE, becoming confused em um teste de resistência falho\./g, s: 'Se você acertar, o alvo deve fazer um teste de resistência de Sabedoria contra a sua CD de MOVE, ficando confundido em um teste de resistência falho.' },
    { r: /You wrap yourself around an enemy Pokémon, trying to squeeze the life from them\./g, s: 'Você se enrola em um Pokémon inimigo, tentando espremer a vida dele.' },
    { r: /Em um acerto, o alvo recebe (.*) and is grappled and restrained by you\./g, s: 'Em um acerto, o alvo recebe $1 e fica agarrado e impedido por você.' },
    { r: /You read into your own abilities and adapt yourself to fit them\./g, s: 'Você analisa suas próprias habilidades e se adapta a elas.' },
    { r: /Choose one of your moves that you know\. For the duração you exchange your typing \(both types if applicable\) for the single type of that move\./g, s: 'Escolha um de seus movimentos conhecidos. Pela duração, você troca sua tipagem (ambos os tipos, se aplicável) pelo tipo único desse movimento.' },
    { r: /With this change all of your previous resistances and vulnerabilities are exchanged for those of your new typing\./g, s: 'Com esta mudança, todas as suas resistências e vulnerabilidades anteriores são trocadas pelas de sua nova tipagem.' },
    { r: /You analyze your opponent's açãos and adapt yourself accordingly\./g, s: 'Você analisa as ações de seu oponente e se adapta de acordo.' },
    { r: /After an enemy Pokémon uses a move you may use your reação to change your typing to random type that is resistant or immune to the type of that move \(if such a type exists\)\./g, s: 'Depois que um Pokémon inimigo usa um movimento, você pode usar sua reação para mudar sua tipagem para um tipo aleatório que seja resistente ou imune ao tipo desse movimento (se tal tipo existir).' },
    { r: /Anything you can do I can do better\./g, s: 'Qualquer coisa que você possa fazer, eu posso fazer melhor.' },
    { r: /You use the move that was most recently used in this battle if that move has a move time of one ação\./g, s: 'Você usa o movimento que foi usado mais recentemente nesta batalha, se esse movimento tiver um tempo de execução de uma ação.' },
    { r: /You call upon the powers of the cosmos to shelter you\./g, s: 'Você invoca os poderes do cosmos para protegê-lo.' },
    { r: /You gain advantage on Constituição, Destreza, and Sabedoria teste de resistências while you maintain Concentração on this move\./g, s: 'Você ganha vantagem em testes de resistência de Constituição, Destreza e Sabedoria enquanto mantiver a concentração neste movimento.' },
    { r: /You surround yourself with a thick coat of wool\./g, s: 'Você se cerca com uma espessa camada de lã.' },
    { r: /You get \+4 AC for the duração\./g, s: 'Você recebe +4 na CA pela duração.' },
    { r: /You let out a cloud of sticky spores towards an opponent\./g, s: 'Você solta uma nuvem de esporos pegajosos em direção a um oponente.' },
    { r: /The target makes a Destreza teste de resistência contra a sua CD de MOVE\./g, s: 'O alvo faz um teste de resistência de Destreza contra a sua CD de MOVE.' },
    { r: /Em uma falha it's deslocamento is halved for the duração as the spores cover it in a sticky solution\./g, s: 'Em uma falha, o deslocamento dele é reduzido pela metade pela duração enquanto os esporos o cobrem com uma solução pegajosa.' },
    { r: /A creature affected by the spores can repeat the teste de resistência at the end of its turn to remove the spores\./g, s: 'Uma criatura afetada pelos esporos pode repetir o teste de resistência no final de cada um de seus turnos para remover os esporos.' },
    { r: /After being attacked you use your reflexes and retaliate against your foe\./g, s: 'Depois de ser atacado, você usa seus reflexos e revida contra seu inimigo.' },
    { r: /After an enemy attacks you with a move that uses Força or Destreza as its MOVE power you may use your reação to Faça uma jogada de ataque corpo a corpo against that opponent\./g, s: 'Depois que um inimigo o ataca com um movimento que usa Força ou Destreza como seu poder de MOVE, você pode usar sua reação para fazer uma jogada de ataque corpo a corpo contra esse oponente.' },
    { r: /You just want it more then they do\./g, s: 'Você simplesmente quer mais do que eles.' },
    { r: /If you hit you may take one of the items the target is holding\./g, s: 'Se você acertar, pode pegar um dos itens que o alvo está segurando.' },
    { r: /You may not use this item until the end of this battle\./g, s: 'Você não pode usar este item até o fim desta batalha.' },
    { r: /You bring the pain by slam down your claw\./g, s: 'Você traz a dor ao descer sua garra com força.' },
    { r: /This move crits on a natural roll of 18, 19, or 20\./g, s: 'Este movimento causa um acerto crítico em uma rolagem natural de 18, 19 ou 20.' },
    { r: /You construct an forcefield of an odd feeling pink energy\./g, s: 'Você constrói um campo de força de uma energia rosa de sensação estranha.' },
    { r: /Any creature within a 30 ft sphere originating from yourself is immune to being poisoned, frozen, confused, burned, asleep, flinched, and paralyzed as long as you maintain Concentração\./g, s: 'Qualquer criatura dentro de uma esfera de 30 pés originando de você mesmo está imune a ser envenenada, congelada, confundida, queimada, adormecida, recuada e paralisada enquanto você mantiver a concentração.' },
    { r: /You bring both your arms down in a devastating double chop\./g, s: 'Você desce ambos os braços em um golpe duplo devastador.' },
    { r: /Faça uma jogada de ataque corpo a corpo at -5 to hit, causando (.*) em um acerto bem-sucedido\./g, s: 'Faça uma jogada de ataque corpo a corpo com -5 para atingir, causando $1 em um acerto bem-sucedido.' },
    { r: /You slash with two poison tipped limbs across the enemy\./g, s: 'Você corta o inimigo com dois membros com pontas venenosas.' },
    { r: /If you hit your target must make a DC 8 Constituição teste de resistência, becoming poisoned em um teste de resistência falho\./g, s: 'Se você acertar, seu alvo deve fazer um teste de resistência de Constituição DC 8, ficando envenenado em um teste de resistência falho.' },

    // Batch 2 (moves_chunk_1.json starting phrases)
    { r: /You sink your teeth into an enemy Pokémon\./g, s: 'Você crava seus dentes em um Pokémon inimigo.' },
    { r: /You crush your opponent's defenses with the Força of your claw swipe\./g, s: 'Você esmaga as defesas do seu oponente com a força do golpe de sua garra.' },
    { r: /Faça uma jogada de ataque corpo a corpo against an opponent dentro do alcance\./g, s: 'Faça uma jogada de ataque corpo a corpo contra um oponente dentro do alcance.' },
    { r: /On a natural roll of 19 to 20 your target takes a -2 penalty to their AC for the duração of this move it you hit them\./g, s: 'Em uma rolagem natural de 19 a 20, seu alvo recebe uma penalidade de -2 na CA pela duração deste movimento se você o atingir.' },
    { r: /You twist fates and throw a curse on the battle\./g, s: 'Você distorce os destinos e lança uma maldição na batalha.' },
    { r: /You touch a creature, and that creature must succeed on a Sabedoria teste de resistência or become cursed for the duração of the spell\./g, s: 'Você toca uma criatura, e essa criatura deve ser bem-sucedida em um teste de resistência de Sabedoria ou ficará amaldiçoada pela duração do feitiço.' },
    { r: /When you cast this spell, choose the nature of the curse from the following options\./g, s: 'Quando você conjura este feitiço, escolha a natureza da maldição entre as seguintes opções.' },
    { r: /• Choose one ability score\. While cursed, the target has disadvantage on Ability Checks and teste de resistências made with that ability score\./g, s: '• Escolha um valor de habilidade. Enquanto amaldiçoado, o alvo tem desvantagem em testes de habilidade e testes de resistência feitos com esse valor de habilidade.' },
    { r: /• While cursed, the target has disadvantage on Attack rolls against you\./g, s: '• Enquanto amaldiçoado, o alvo tem desvantagem em jogadas de ataque contra você.' },
    { r: /• While cursed, the target must make a Sabedoria teste de resistência at the start of each of its turns\. If it fails, it wastes its ação that turn doing nothing\./g, s: '• Enquanto amaldiçoado, o alvo deve fazer um teste de resistência de Sabedoria no início de cada um de seus turnos. Se falhar, ele desperdiça sua ação naquele turno sem fazer nada.' },
    { r: /• While the target is cursed, your attacks deal an extra 1d8 necrotic damage to the target\./g, s: '• Enquanto o alvo estiver amaldiçoado, seus ataques causam 1d8 de dano necrótico extra ao alvo.' },
    { r: /no nível 5 the duração aumenta para 10 minutes \(Concentração\), at 11th level the duração aumenta para 8 hours \(Concentração\), and at 17th level the duração aumenta para 24 hours \(Concentração\)\./g, s: 'No nível 5 a duração aumenta para 10 minutos (Concentração), no nível 11 a duração aumenta para 8 horas (Concentração) e no nível 17 a duração aumenta para 24 horas (Concentração).' },
    { r: /You lash out at an enemy with vine,claw, or blade\./g, s: 'Você ataca um inimigo com chicote, garra ou lâmina.' },
    { r: /Make a melee roll on an enemy, causando (.*) em um acerto bem-sucedido\./g, s: 'Faça uma rolagem corpo a corpo contra um inimigo, causando $1 em um acerto bem-sucedido.' },
    { r: /You send out a wave of dark energy\./g, s: 'Você envia uma onda de energia sombria.' },
    { r: /Each creature in your choice of in a sphere of radius 10 pés centered on yourself makes a Charisma teste de resistência\./g, s: 'Cada criatura de sua escolha em uma esfera de raio de 10 pés centrada em você mesmo faz um teste de resistência de Carisma.' },
    { r: /Em uma falha they take (.*) or half as much em um sucesso\./g, s: 'Em uma falha, elas recebem $1 ou metade disso em um sucesso.' },
    { r: /You extend your arms in a t-pose and spin, striking your opponent with your outstretched hands\./g, s: 'Você estende os braços em posição de T e gira, atingindo o oponente com as mãos estendidas.' },
    { r: /This move ignores any bonuses to the target's AC \(such as other move's effects or feats\), always hitting the species' natural AC\./g, s: 'Este movimento ignora quaisquer bônus na CA do alvo (como efeitos de outros movimentos ou talentos), sempre atingindo a CA natural da espécie.' },
    { r: /You bite with a maw filled with roaring flame\./g, s: 'Você morde com uma mandíbula cheia de chamas rugintes.' },
    { r: /Faça uma jogada de ataque corpo a corpo, doing (.*)\. On a natural roll of 17 or higher this move flinches any Pokémon it hits\./g, s: 'Faça uma jogada de ataque corpo a corpo, causando $1. Em uma rolagem natural de 17 ou superior, este movimento faz recuar qualquer Pokémon que atingir.' },
    { r: /You strike out with a whip of pure fire\./g, s: 'Você golpeia com um chicote de fogo puro.' },
    { r: /This move has a range of melee but can reach targets up to 15 pés from the user, rather than the normal 5 pés\./g, s: 'Este movimento tem alcance corpo a corpo, mas pode atingir alvos a até 15 pés do usuário, em vez dos normais 5 pés.' },
    { r: /You call upon your allies as you release the essence of fire\./g, s: 'Você invoca seus aliados enquanto libera a essência do fogo.' },
    { r: /If you hit and one of your allies has done damage to your target with either Water Pledge or Grass Pledge in the past minute, any creature within 10 ft of the target also takes your Fire Pledge damage\./g, s: 'Se você acertar e um de seus aliados tiver causado dano ao seu alvo com Compromisso de Água ou Compromisso de Planta no último minuto, qualquer criatura a até 10 pés do alvo também recebe o dano do seu Compromisso de Fogo.' },
    { r: /If the target has been hit by both Water Pledge and Grass Pledge in the past minute the radius of creatures taking damage aumenta para 20 ft\./g, s: 'Se o alvo tiver sido atingido tanto pelo Compromisso de Água quanto pelo Compromisso de Planta no último minuto, o raio de criaturas recebendo dano aumenta para 20 pés.' },
    { r: /You strike out with fire infused fists\./g, s: 'Você golpeia com punhos infundidos de fogo.' },
    { r: /If you hit with this attack your target must make a DC 10 Constituição teste de resistência or become burned\./g, s: 'Se você acertar com este ataque, seu alvo deve fazer um teste de resistência de Constituição DC 10 ou ficará queimado.' },
    { r: /You release a series of moving flames that dance around a target\./g, s: 'Você libera uma série de chamas móveis que dançam ao redor de um alvo.' },
    { r: /Em um acerto and restraining the target\./g, s: 'em um acerto e impedindo o alvo.' },
    { r: /A creature Restrained by this move can use its açãos to make a Força check contra a sua CD de MOVE\./g, s: 'Uma criatura impedida por este movimento pode usar suas ações para fazer um teste de Força contra a sua CD de MOVE.' },
    { r: /If it succeeds, it is no longer Restrained\./g, s: 'Se for bem-sucedida, não estará mais impedida.' },
    { r: /While you are restraining a creature with this move, you may spend your ação to attack that creature again with this move without spending an additional PP\./g, s: 'Enquanto você estiver impedindo uma criatura com este movimento, você pode gastar sua ação para atacar essa criatura novamente com este movimento sem gastar PP adicional.' },
    { r: /You strike quickly against your opponent, tearing into them before they can react\./g, s: 'Você golpeia rapidamente seu oponente, rasgando-o antes que ele possa reagir.' },
    { r: /You may move up to your movement speed before making a melee attack roll, causando (.*) em um acerto\./g, s: 'Você pode se mover até seu deslocamento antes de fazer uma jogada de ataque corpo a corpo, causando $1 em um acerto.' },
    { r: /This attack can only be used during the first turn of a battle\./g, s: 'Este ataque só pode ser usado durante o primeiro turno de uma batalha.' },
    { r: /You crack open the natural faults in the ground with devastating force\./g, s: 'Você abre as falhas naturais no solo com força devastadora.' },
    { r: /You creatue a fissure which is 10 pés wide 80 pés long, and 1d6 times 10 pés deep\./g, s: 'Você cria uma fissura que tem 10 pés de largura, 80 pés de comprimento e 1d6 vezes 10 pés de profundidade.' },
    { r: /A creature standing on a spot where a fissure opens must succeed on a Destreza teste de resistência contra a sua CD de MOVE or fall in\./g, s: 'Uma criatura em um local onde uma fissura se abre deve ser bem-sucedida em um teste de resistência de Destreza contra a sua CD de MOVE ou cairá nela.' },
    { r: /A creature that successfully saves moves with the fissure's edge as it opens\./g, s: 'Uma criatura que passar no teste se move para a borda da fissura enquanto ela se abre.' },
    { r: /The depth for the fissure aumenta para 1d12 times 10 no nível 11\./g, s: 'A profundidade da fissura aumenta para 1d12 vezes 10 no nível 11.' },
    { r: /You helplessly flail your limbs about\./g, s: 'Você agita seus membros desamparadamente.' },
    { r: /Em um acerto deal (.*) normal damage\./g, s: 'Em um acerto, causa $1 de dano normal.' },
    { r: /If you are below 10 hp, this attack is automatically a critical em um acerto\./g, s: 'Se você estiver com menos de 10 PV, este ataque é automaticamente um crítico em um acerto.' },
    { r: /You lob a glob of oddly shaped fire\./g, s: 'Você lança um globo de fogo de formato estranho.' },
    { r: /Any Pokémon caught in the line must succeed on a DEX teste de resistência contra a sua CD de MOVE, taking (.*) em um teste de resistência falho, or half damage em um sucesso\./g, s: 'Qualquer Pokémon pego na linha deve ser bem-sucedido em um teste de resistência de Destreza contra a sua CD de MOVE, recebendo $1 em um teste de resistência falho ou metade do dano em um sucesso.' },
    { r: /If any of the targets fails the teste de resistência by 5 or more they become burnt\./g, s: 'Se algum dos alvos falhar no teste de resistência por 5 ou mais, ele ficará queimado.' },
    { r: /You surround yourself in flame and attack in an all-out charge\./g, s: 'Você se cerca de chamas e ataca em uma investida total.' },
    { r: /If you moved at least 10 pés before you made the attack you gain 10 pés of movement speed in your main form of locomotion until the end of your next turn\./g, s: 'Se você se moveu pelo menos 10 pés antes de realizar o ataque, você ganha 10 pés de deslocamento em sua forma principal de locomoção até o final do seu próximo turno.' },
    { r: /You gather flame around yourself and spin into a ball of fire\./g, s: 'Você reúne chamas ao seu redor e gira em uma bola de fogo.' },
    { r: /You may move up to 10 ft before attacking an opponent\./g, s: 'Você pode se mover até 10 pés antes de atacar um oponente.' },
    { r: /If you hit your target they must make a DC 11 Constituição teste de resistência, becoming burned em uma falha\./g, s: 'Se você atingir seu alvo, ele deve fazer um teste de resistência de Constituição DC 11, ficando queimado em uma falha.' },
    { r: /You shoot a concentrated gout of flame in an 80 foot line, 5 pés wide\./g, s: 'Você dispara um jato concentrado de chamas em uma linha de 80 pés com 5 pés de largura.' },
    { r: /Any Pokémon caught in the line must succeed on a DEX save contra a sua CD de MOVE, taking (.*) em um teste de resistência falho, or half damage em um sucesso\./g, s: 'Qualquer Pokémon pego na linha deve ser bem-sucedido em um teste de resistência de Destreza contra a sua CD de MOVE, recebendo $1 em um teste de resistência falho ou metade do dano em um sucesso.' },
    { r: /If any target fails the teste de resistência by 5 or more, they become burned\./g, s: 'Se algum alvo falhar no teste de resistência por 5 ou mais, ele ficará queimado.' },
    { r: /As your body burns like the sun you pummel an opponent\./g, s: 'Enquanto seu corpo queima como o sol, você golpeia um oponente.' },
    { r: /As part of this move you may use your bonus ação to make two additional melee attacks\./g, s: 'Como parte deste movimento, você pode usar sua ação bônus para realizar dois ataques corpo a corpo adicionais.' },
    { r: /On each hit you deal (.*) to the target\./g, s: 'A cada acerto, você causa $1 ao alvo.' },
    { r: /You emit an immense flash of light in a 10 foot radius circle, centered on you\./g, s: 'Você emite um imenso flash de luz em um círculo de 10 pés de raio, centrado em você.' },
    { r: /Creatures in the area must make a Constituição teste de resistência contra a sua CD de MOVE\./g, s: 'As criaturas na área devem fazer um teste de resistência de Constituição contra a sua CD de MOVE.' },
    { r: /Em um teste de resistência falho, they are blinded\./g, s: 'Em um teste de resistência falho, elas ficam cegas.' },
    { r: /A creature can remove this blindness by retrying the teste de resistência at the end of each of its turns\./g, s: 'Uma criatura pode remover esta cegueira repetindo o teste de resistência no final de cada um de seus turnos.' },
    { r: /You convert the light hitting your body into a beam of energy which you fire at the enemy Pokémon\./g, s: 'Você converte a luz que atinge seu corpo em um feixe de energia que dispara contra o Pokémon inimigo.' },
    { r: /Target a point of space dentro do alcance\./g, s: 'Alveje um ponto no espaço dentro do alcance.' },
    { r: /Each creature within a 10 foot radius sphere originating from that point makes a Constituição teste de resistência contra a sua CD de MOVE, taking (.*) em um teste de resistência falho and half as much em um sucessoful one\./g, s: 'Cada criatura em uma esfera de raio de 10 pés originando desse ponto faz um teste de resistência de Constituição contra a sua CD de MOVE, recebendo $1 em um teste de resistência falho e metade disso em um sucesso.' },
    { r: /You shower praises on your opponent an try to throw off their rhythm\./g, s: 'Você despeja elogios em seu oponente e tenta quebrar seu ritmo.' },
    { r: /One target of your choice makes a Sabedoria teste de resistência contra a sua CD de MOVE becoming confused em uma falha\./g, s: 'Um alvo de sua escolha faz um teste de resistência de Sabedoria contra a sua CD de MOVE, ficando confundido em uma falha.' },
    { r: /If your target becomes confused, it has disadvantage on teste de resistências during the confusion\./g, s: 'Se o seu alvo ficar confundido, ele tem desvantagem em testes de resistência durante a confusão.' },
    { r: /You fling whatever you can find at your opponent\./g, s: 'Você lança o que puder encontrar em seu oponente.' },
    { r: /Faça uma jogada de ataque à distância dealing (.*) em um acerto\./g, s: 'Faça uma jogada de ataque à distância causando $1 em um acerto.' },
    { r: /If you are holding a held item you may fling that item, dealing an extra 1d6 dano sombrio and getting a \+10 to hit\./g, s: 'Se você estiver segurando um item, poderá lançar esse item, causando 1d6 de dano sombrio extra e recebendo +10 no acerto.' },
    { r: /You use your natural gifts with flowers and medicine to heal a friend\./g, s: 'Você usa seus dons naturais com flores e medicina para curar um amigo.' },
    { r: /One ally dentro do alcance heals (.*) HP\./g, s: 'Um aliado dentro do alcance cura $1 PV.' },
    { r: /You use the power of flowers to protect your allies\./g, s: 'Você usa o poder das flores para proteger seus aliados.' },
    { r: /You and each creature you choose within 5 pés of you gains \+1 AC for the duração\./g, s: 'Você e cada criatura que você escolher a até 5 pés de você ganham +1 na CA pela duração.' },
    { r: /Your targets do not need to stay in range to maintain this bonus\./g, s: 'Seus alvos não precisam permanecer no alcance para manter este bônus.' },
    { r: /If any of your targets are grass type they gain \+2 AC instead\./g, s: 'Se algum dos seus alvos for do tipo planta, ele ganha +2 na CA em vez disso.' },
    { r: /You fly high into the air to prepare for a dive bomb attack\./g, s: 'Você voa alto no ar para se preparar para um ataque de mergulho.' },
    { r: /When you activate this move, you flap your wings and disappear into the elemental plane of air above you\./g, s: 'Quando você ativa este movimento, você bate as asas e desaparece no plano elemental do ar acima de você.' },
    { r: /At the start of you next turn you return to an unoccupied space of your choice within 30 pés of the space you vanished from\./g, s: 'No início do seu próximo turno, você retorna para um espaço desocupado de sua escolha a até 30 pés do espaço de onde desapareceu.' },
    { r: /When you reappear you may immediately use your ação to make a diving melee attack, fazendo fazendo (.*) em um acerto bem-sucedido\./g, s: 'Quando você reaparece, você pode usar imediatamente sua ação para fazer um ataque corpo a corpo em mergulho, causando $1 em um acerto bem-sucedido.' },
    { r: /You are Hawlucha, master of the ring\./g, s: 'Você é Hawlucha, o mestre do ringue.' },
    { r: /You leap into the air and unleash your signature attack upon your return to the ground\./g, s: 'Você pula no ar e libera seu ataque característico ao retornar ao solo.' },
    { r: /You may either fly or walk up to 15 pÃ©s and then Faça uma jogada de ataque corpo a corpo\./g, s: 'Você pode voar ou caminhar até 15 pés e então fazer uma jogada de ataque corpo a corpo.' },
    { r: /You focus your ki into a slow moving, concentrated blast\./g, s: 'Você foca seu ki em uma explosão concentrada de movimento lento.' },
    { r: /Faça uma jogada de ataque à distância against an opponent at disadvantage\. Em um acerto you deal (.*)\./g, s: 'Faça uma jogada de ataque à distância contra um oponente com desvantagem. Em um acerto, você causa $1.' },
    { r: /You sacrifice your ação to focus in on the energy inside you\./g, s: 'Você sacrifica sua ação para se concentrar na energia dentro de você.' },
    { r: /For the duração, you roll a critical hit on natural attack rolls of 19 and 20\./g, s: 'Pela duração, você rola um acerto crítico em jogadas de ataque naturais de 19 e 20.' },
    { r: /You hold fast and focus your energy onto the enemy in front of your\./g, s: 'Você se mantém firme e foca sua energia no inimigo à sua frente.' },
    { r: /Until your next turn if you hit a creature with an opportunity attack the creature's deslocamento becomes 0 for the rest of the turn\./g, s: 'Até o seu próximo turno, se você atingir uma criatura com um ataque de oportunidade, o deslocamento da criatura torna-se 0 pelo resto do turno.' },
    { r: /As your next turn's ação, if you keep your Concentração, you unleash your energy in a powerful strike\./g, s: 'Como ação do seu próximo turno, se você mantiver sua concentração, você libera sua energia em um golpe poderoso.' },
    { r: /You make a big ruckus to make yourself the center of attention\./g, s: 'Você faz um grande alvoroço para se tornar o centro das atenções.' },
    { r: /Each enemy creature within 30 pés of yourself must make a Sabedoria teste de resistência\./g, s: 'Cada criatura inimiga a até 30 pés de você deve fazer um teste de resistência de Sabedoria.' },
    { r: /Em um teste de resistência falho they having disadvantage on attack rolls against any creature except yourself for the duração\./g, s: 'Em um teste de resistência falho, elas têm desvantagem em jogadas de ataque contra qualquer criatura exceto você pela duração.' },
    { r: /You strike with an open hand, precision striking the enemy's pressure points\./g, s: 'Você golpeia com a mão aberta, atingindo com precisão os pontos de pressão do inimigo.' },
    { r: /If the opponent takes damage they must make a Constituição teste de resistência of DC 10 \+ your Inteligência modifier\./g, s: 'Se o oponente receber dano, ele deve fazer um teste de resistência de Constituição DC 10 + seu modificador de Inteligência.' },
    { r: /You see through the veil\./g, s: 'Você vê através do véu.' },
    { r: /If that Pokémon was ghost type, you can deal normal and fighting damage to it as if it didn't have those immunities for the duração of this move\./g, s: 'Se esse Pokémon for do tipo fantasma, você pode causar dano normal e lutador a ele como se ele não tivesse essas imunidades pela duração deste movimento.' }
];

function refine(text) {
    let result = text;
    for (const rep of replacements) {
        result = result.replace(rep.r, rep.s);
    }
    // Final cleanup for common mechanical artifacts
    result = result.replace(/dano (planta|pedra|veneno|voador|sombrio|fantasma|inseto|lutador|gelo|aço|água|normal|psíquico|elétrico|fogo|dragão|terra|fada)/g, 'dano de $1');
    result = result.replace(/dano de voador/g, 'dano voador');
    result = result.replace(/dano de sombrio/g, 'dano sombrio');
    result = result.replace(/dano de fantasma/g, 'dano fantasma');
    result = result.replace(/dano de lutador/g, 'dano lutador');
    result = result.replace(/dano de normal/g, 'dano normal');
    result = result.replace(/dano de psíquico/g, 'dano psíquico');
    
    // Fix multi-word types
    result = result.replace(/dano de de/g, 'dano de');
    
    // Fix common English leftovers not caught by patterns
    result = result.replace(/\band\b/g, 'e');
    result = result.replace(/\bwith\b/g, 'com');
    result = result.replace(/\bdoing\b/g, 'causando');
    result = result.replace(/\bin\b/g, 'em');
    result = result.replace(/\bthe\b/g, 'o');
    result = result.replace(/\ba\b/g, 'um');
    result = result.replace(/\bon\b/g, 'em');
    result = result.replace(/\bat\b/g, 'em');
    result = result.replace(/\bfrom\b/g, 'de');
    result = result.replace(/\bwithin\b/g, 'dentro de');
    result = result.replace(/\bfeet\b/g, 'pés');
    result = result.replace(/\bfoot\b/g, 'pé');
    result = result.replace(/\blevel\b/g, 'nível');
    result = result.replace(/\baction\b/g, 'ação');
    result = result.replace(/\bbonus ação\b/g, 'ação bônus');
    result = result.replace(/\breação\b/g, 'reação');
    result = result.replace(/\bsuccessful hit\b/g, 'acerto bem-sucedido');
    result = result.replace(/\bhit\b/g, 'acerto');
    result = result.replace(/\bfailure\b/g, 'falha');
    result = result.replace(/\bsuccess\b/g, 'sucesso');
    
    return result;
}

files.forEach(file => {
    const filePath = path.join(__dirname, file);
    if (!fs.existsSync(filePath)) return;
    
    const content = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(content);
    
    data.forEach(move => {
        if (move.description && move.description.pt) {
            move.description.pt = refine(move.description.pt);
        }
        if (move.higherLevels && move.higherLevels.pt) {
            move.higherLevels.pt = refine(move.higherLevels.pt);
        }
    });
    
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
});
